volumes:
  pg_data:
    external: true
  redis_data:
    external: true

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
    command: postgres -c max_prepared_transactions=100
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    networks:
      - db

  # redis:
  #   container_name: redis
  #   image: bitnami/redis:latest
  #   restart: always
  #   ports:
  #     - '${REDIS_PORT}:6379'
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASS}
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - db

networks:
  db:
    external: true